# Generated by Django 5.1.4 on 2024-12-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veille_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='Medium', max_length=50),
        ),
    ]
